name: Build Puzzle Archive

on:
  push:
    branches:
      - main
    paths:
      - 'puzzles/**'  # watch this directory

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to create releases
    
    steps:
      - uses: actions/checkout@v5
      - name: Create zip archive
        run: zip -r puzzles.zip puzzles/      
      - name: Update Latest Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: puzzles.zip
          body: "Latest puzzle archive"
